### ISSUE TITLE
Campagne créé ne s'affiche pas

### ISSUE THREAD

**Issue by DimitriP-dev** [AlexKlii/TuneTogether#19]
**Describe the bug**
Après avoir créé une campagne, je ne parviens à l'afficher dans "Search a campaign".

**To Reproduce**
1. Cliquer sur "Start a campaign"
2. Remplir tous les champs
3. Remplir tous les champs
4. Cliquer sur Submit Campaign
5. Payer les fees sur MetaMask (accepter 2 transactions)
6. Cliquer sur Search a campaign

**Expected behavior**
La campagne est censé s'afficher pour l'utilisateur après création.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Brave]
 - Version [1.52.130]

**Additional context**
N/A

**Comment by AlexKlii** [comment]
Resolved in [PR#21](https://github.com/AlexKlii/TuneTogether/pull/21) :white_check_mark:
